export const ADD_SERVICE = 'ADD_SERVICE'
export const REMOVE_SERVICE = 'REMOVE_SERVICE'
export const EDIT_SERVICE = 'EDIT_SERVICE'

export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD'
export const DELLETING_SERVICE_FIELD = 'DELLETING_SERVICE_FIELD'
export const EDIT_SERVICE_FIELD = 'EDIT_SERVICE_FIELD'

export const EDIT_CHECK_SERVICE = 'EDIT_CHECK_SERVICE'